name = "loom"
version = "0.1.0"

description = "A flexible and optimized Trie implementation for the Gleam programming language."
licences = ["MIT"]
repository = { type = "github", user = "penguinawesome1", repo = "loom" }
links = [{ title = "Demo", href = "https://penguinawesome1.github.io/loom/" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"

